/**
 * Generated by Verge3D Puzzles v.3.6.1
 * Tue Jan 11 2022 01:40:17 GMT-0500 (hora estándar de Perú)
 * Prefer not editing this file as your changes may get overridden once Puzzles are saved.
 * Check out https://www.soft8soft.com/docs/manual/en/introduction/Using-JavaScript.html
 * for the information on how to add your own JavaScript to Verge3D apps.
 */

'use strict';

(function() {

// global variables/constants used by puzzles' functions

var LIST_NONE = '<none>';

var _pGlob = {};

_pGlob.objCache = {};
_pGlob.fadeAnnotations = true;
_pGlob.pickedObject = '';
_pGlob.hoveredObject = '';
_pGlob.mediaElements = {};
_pGlob.loadedFile = '';
_pGlob.states = [];
_pGlob.percentage = 0;
_pGlob.openedFile = '';
_pGlob.xrSessionAcquired = false;
_pGlob.xrSessionCallbacks = [];
_pGlob.screenCoords = new v3d.Vector2();
_pGlob.intervalTimers = {};

_pGlob.AXIS_X = new v3d.Vector3(1, 0, 0);
_pGlob.AXIS_Y = new v3d.Vector3(0, 1, 0);
_pGlob.AXIS_Z = new v3d.Vector3(0, 0, 1);
_pGlob.MIN_DRAG_SCALE = 10e-4;
_pGlob.SET_OBJ_ROT_EPS = 1e-8;

_pGlob.vec2Tmp = new v3d.Vector2();
_pGlob.vec2Tmp2 = new v3d.Vector2();
_pGlob.vec3Tmp = new v3d.Vector3();
_pGlob.vec3Tmp2 = new v3d.Vector3();
_pGlob.vec3Tmp3 = new v3d.Vector3();
_pGlob.vec3Tmp4 = new v3d.Vector3();
_pGlob.eulerTmp = new v3d.Euler();
_pGlob.eulerTmp2 = new v3d.Euler();
_pGlob.quatTmp = new v3d.Quaternion();
_pGlob.quatTmp2 = new v3d.Quaternion();
_pGlob.colorTmp = new v3d.Color();
_pGlob.mat4Tmp = new v3d.Matrix4();
_pGlob.planeTmp = new v3d.Plane();
_pGlob.raycasterTmp = new v3d.Raycaster();

var PL = v3d.PL = v3d.PL || {};

// a more readable alias for PL (stands for "Puzzle Logic")
v3d.puzzles = PL;

PL.procedures = PL.procedures || {};




PL.execInitPuzzles = function(options) {
    // always null, should not be available in "init" puzzles
    var appInstance = null;
    // app is more conventional than appInstance (used in exec script and app templates)
    var app = null;

    var _initGlob = {};
    _initGlob.percentage = 0;
    _initGlob.output = {
        initOptions: {
            fadeAnnotations: true,
            useBkgTransp: false,
            preserveDrawBuf: false,
            useCompAssets: false,
            useFullscreen: true,
            useCustomPreloader: false,
            preloaderStartCb: function() {},
            preloaderProgressCb: function() {},
            preloaderEndCb: function() {},
        }
    }

    // provide the container's id to puzzles that need access to the container
    _initGlob.container = options !== undefined && 'container' in options
            ? options.container : "";

    

    var PROC = {
    
};


// utility functions envoked by the HTML puzzles
function getElements(ids, isParent) {
    var elems = [];
    if (Array.isArray(ids) && ids[0] != 'CONTAINER' && ids[0] != 'WINDOW' &&
        ids[0] != 'DOCUMENT' && ids[0] != 'BODY' && ids[0] != 'QUERYSELECTOR') {
        for (var i = 0; i < ids.length; i++)
            elems.push(getElement(ids[i], isParent));
    } else {
        elems.push(getElement(ids, isParent));
    }
    return elems;
}

function getElement(id, isParent) {
    var elem;
    if (Array.isArray(id) && id[0] == 'CONTAINER') {
        if (appInstance !== null) {
            elem = appInstance.container;
        } else if (typeof _initGlob !== 'undefined') {
            // if we are on the initialization stage, we still can have access
            // to the container element
            var id = _initGlob.container;
            if (isParent) {
                elem = parent.document.getElementById(id);
            } else {
                elem = document.getElementById(id);
            }
        }
    } else if (Array.isArray(id) && id[0] == 'WINDOW') {
        if (isParent)
            elem = parent;
        else
            elem = window;
    } else if (Array.isArray(id) && id[0] == 'DOCUMENT') {
        if (isParent)
            elem = parent.document;
        else
            elem = document;
    } else if (Array.isArray(id) && id[0] == 'BODY') {
        if (isParent)
            elem = parent.document.body;
        else
            elem = document.body;
    } else if (Array.isArray(id) && id[0] == 'QUERYSELECTOR') {
        if (isParent)
            elem = parent.document.querySelector(id);
        else
            elem = document.querySelector(id);
    } else {
        if (isParent)
            elem = parent.document.getElementById(id);
        else
            elem = document.getElementById(id);
    }
    return elem;
}



// setHTMLElemAttribute puzzle
function setHTMLElemAttribute(attr, value, ids, isParent) {
    var elems = getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem) continue;

        if (attr === 'style') {
            // NOTE: setting an attribute 'style' instead of a property 'style'
            // fixes IE11 wrong behavior
            elem.setAttribute(attr, value);
        } else if ((attr == 'href' || attr == 'src') && value instanceof Promise) {
            // resolve promise value for url-based attributes
            value.then(function(response) {
                elem[attr] = response;
            });
        } else {
            elem[attr] = value;
        }
    }
}



// setHTMLElemStyle puzzle
function setHTMLElemStyle(prop, value, ids, isParent) {
    var elems = getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem || !elem.style)
            continue;
        elem.style[prop] = value;
    }
}




// initPreloader puzzle
_initGlob.output.initOptions.useCustomPreloader = true;
_initGlob.output.initOptions.preloaderStartCb = function() {
    _initGlob.percentage = 0;
    (function() {})();
};
_initGlob.output.initOptions.preloaderProgressCb = function(percentage) {
    _initGlob.percentage = percentage;
    (function() {
  setHTMLElemAttribute('innerHTML', String(Math.round(_initGlob.percentage)) + '%', 'loading_percentage', true);
})();
};
_initGlob.output.initOptions.preloaderEndCb = function() {
    _initGlob.percentage = 100;
    (function() {
  setHTMLElemStyle('display', 'none', 'preloader_screen', true);
})();
};


// initSettings puzzle
_initGlob.output.initOptions.fadeAnnotations = false;
_initGlob.output.initOptions.useBkgTransp = false;
_initGlob.output.initOptions.preserveDrawBuf = false;
_initGlob.output.initOptions.useCompAssets = true;
_initGlob.output.initOptions.useFullscreen = false;

    return _initGlob.output;
}

PL.init = function(appInstance, initOptions) {

// app is more conventional than appInstance (used in exec script and app templates)
var app = appInstance;

initOptions = initOptions || {};

if ('fadeAnnotations' in initOptions) {
    _pGlob.fadeAnnotations = initOptions.fadeAnnotations;
}

this.procedures["paso1"] = paso1;
this.procedures["paso2"] = paso2;
this.procedures["paso3"] = paso3;
this.procedures["interactionFunction"] = interactionFunction;
this.procedures["nextAnimation"] = nextAnimation;
this.procedures["paso1animation2"] = paso1animation2;
this.procedures["paso1animation3"] = paso1animation3;
this.procedures["paso2animation1"] = paso2animation1;
this.procedures["paso2animation2"] = paso2animation2;
this.procedures["paso1animation4"] = paso1animation4;
this.procedures["paso2animation3"] = paso2animation3;
this.procedures["paso1animation5"] = paso1animation5;
this.procedures["paso1animation6"] = paso1animation6;
this.procedures["paso1animation7"] = paso1animation7;
this.procedures["paso1animation8"] = paso1animation8;
this.procedures["paso1animation9"] = paso1animation9;
this.procedures["paso3animation1"] = paso3animation1;
this.procedures["paso3animation2"] = paso3animation2;
this.procedures["paso3animation3"] = paso3animation3;

var PROC = {
    "paso1": paso1,
    "paso2": paso2,
    "paso3": paso3,
    "interactionFunction": interactionFunction,
    "nextAnimation": nextAnimation,
    "paso1animation2": paso1animation2,
    "paso1animation3": paso1animation3,
    "paso2animation1": paso2animation1,
    "paso2animation2": paso2animation2,
    "paso1animation4": paso1animation4,
    "paso2animation3": paso2animation3,
    "paso1animation5": paso1animation5,
    "paso1animation6": paso1animation6,
    "paso1animation7": paso1animation7,
    "paso1animation8": paso1animation8,
    "paso1animation9": paso1animation9,
    "paso3animation1": paso3animation1,
    "paso3animation2": paso3animation2,
    "paso3animation3": paso3animation3,
};

var correas, animation_counter, func_steps, func_interaction, func_mouse, func_keyboard, func_next, func_framesFrom, func_framesTo, func_animation_counter, count, pasos, interaction2, interaction3, interaction9, interaction11, interaction10, interaction12, interaction4, interaction5, interaction6, interaction7, interaction8, interaction1;


// utility functions envoked by the HTML puzzles
function getElements(ids, isParent) {
    var elems = [];
    if (Array.isArray(ids) && ids[0] != 'CONTAINER' && ids[0] != 'WINDOW' &&
        ids[0] != 'DOCUMENT' && ids[0] != 'BODY' && ids[0] != 'QUERYSELECTOR') {
        for (var i = 0; i < ids.length; i++)
            elems.push(getElement(ids[i], isParent));
    } else {
        elems.push(getElement(ids, isParent));
    }
    return elems;
}

function getElement(id, isParent) {
    var elem;
    if (Array.isArray(id) && id[0] == 'CONTAINER') {
        if (appInstance !== null) {
            elem = appInstance.container;
        } else if (typeof _initGlob !== 'undefined') {
            // if we are on the initialization stage, we still can have access
            // to the container element
            var id = _initGlob.container;
            if (isParent) {
                elem = parent.document.getElementById(id);
            } else {
                elem = document.getElementById(id);
            }
        }
    } else if (Array.isArray(id) && id[0] == 'WINDOW') {
        if (isParent)
            elem = parent;
        else
            elem = window;
    } else if (Array.isArray(id) && id[0] == 'DOCUMENT') {
        if (isParent)
            elem = parent.document;
        else
            elem = document;
    } else if (Array.isArray(id) && id[0] == 'BODY') {
        if (isParent)
            elem = parent.document.body;
        else
            elem = document.body;
    } else if (Array.isArray(id) && id[0] == 'QUERYSELECTOR') {
        if (isParent)
            elem = parent.document.querySelector(id);
        else
            elem = document.querySelector(id);
    } else {
        if (isParent)
            elem = parent.document.getElementById(id);
        else
            elem = document.getElementById(id);
    }
    return elem;
}



// eventHTMLElem puzzle
function eventHTMLElem(eventType, ids, isParent, callback) {
    var elems = getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem)
            continue;
        elem.addEventListener(eventType, callback);
        if (v3d.PL.editorEventListeners)
            v3d.PL.editorEventListeners.push([elem, eventType, callback]);
    }
}




// utility function envoked by almost all V3D-specific puzzles
// filter off some non-mesh types
function notIgnoredObj(obj) {
    return obj.type !== 'AmbientLight' &&
           obj.name !== '' &&
           !(obj.isMesh && obj.isMaterialGeneratedMesh) &&
           !obj.isAuxClippingMesh;
}


// utility function envoked by almost all V3D-specific puzzles
// find first occurence of the object by its name
function getObjectByName(objName) {
    var objFound;
    var runTime = _pGlob !== undefined;
    objFound = runTime ? _pGlob.objCache[objName] : null;

    if (objFound && objFound.name === objName)
        return objFound;

    appInstance.scene.traverse(function(obj) {
        if (!objFound && notIgnoredObj(obj) && (obj.name == objName)) {
            objFound = obj;
            if (runTime) {
                _pGlob.objCache[objName] = objFound;
            }
        }
    });
    return objFound;
}


// utility function envoked by almost all V3D-specific puzzles
// retrieve all objects on the scene
function getAllObjectNames() {
    var objNameList = [];
    appInstance.scene.traverse(function(obj) {
        if (notIgnoredObj(obj))
            objNameList.push(obj.name)
    });
    return objNameList;
}


// utility function envoked by almost all V3D-specific puzzles
// retrieve all objects which belong to the group
function getObjectNamesByGroupName(targetGroupName) {
    var objNameList = [];
    appInstance.scene.traverse(function(obj){
        if (notIgnoredObj(obj)) {
            var groupNames = obj.groupNames;
            if (!groupNames)
                return;
            for (var i = 0; i < groupNames.length; i++) {
                var groupName = groupNames[i];
                if (groupName == targetGroupName) {
                    objNameList.push(obj.name);
                }
            }
        }
    });
    return objNameList;
}


// utility function envoked by almost all V3D-specific puzzles
// process object input, which can be either single obj or array of objects, or a group
function retrieveObjectNames(objNames) {
    var acc = [];
    retrieveObjectNamesAcc(objNames, acc);
    return acc.filter(function(name) {
        return name;
    });
}

function retrieveObjectNamesAcc(currObjNames, acc) {
    if (typeof currObjNames == "string") {
        acc.push(currObjNames);
    } else if (Array.isArray(currObjNames) && currObjNames[0] == "GROUP") {
        var newObj = getObjectNamesByGroupName(currObjNames[1]);
        for (var i = 0; i < newObj.length; i++)
            acc.push(newObj[i]);
    } else if (Array.isArray(currObjNames) && currObjNames[0] == "ALL_OBJECTS") {
        var newObj = getAllObjectNames();
        for (var i = 0; i < newObj.length; i++)
            acc.push(newObj[i]);
    } else if (Array.isArray(currObjNames)) {
        for (var i = 0; i < currObjNames.length; i++)
            retrieveObjectNamesAcc(currObjNames[i], acc);
    }
}




// outline puzzle
function outline(objSelector, doWhat) {
    var objNames = retrieveObjectNames(objSelector);

    if (!appInstance.postprocessing || !appInstance.postprocessing.outlinePass)
        return;
    var outlineArray = appInstance.postprocessing.outlinePass.selectedObjects;
    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i];
        var obj = getObjectByName(objName);
        if (!obj)
            continue;
        if (doWhat == "ENABLE") {
            if (outlineArray.indexOf(obj) == -1)
                outlineArray.push(obj);
        } else {
            var index = outlineArray.indexOf(obj);
            if (index > -1)
                outlineArray.splice(index, 1);
        }
    }
}



// getAnimations puzzle
function getAnimations(objSelector) {
    var objNames = retrieveObjectNames(objSelector);

    var animations = [];
    for (var i = 0; i < objNames.length; i++) {
        var objName = objNames[i];
        if (!objName)
            continue;
        // use objName as animName - for now we have one-to-one match
        var action = v3d.SceneUtils.getAnimationActionByName(appInstance, objName);
        if (action)
            animations.push(objName);
    }
    return animations;
}



/**
 * Get a scene that contains the root of the given action.
 */
function getSceneByAction(action) {
    var root = action.getRoot();
    var scene = root.type == "Scene" ? root : null;
    root.traverseAncestors(function(ancObj) {
        if (ancObj.type == "Scene") {
            scene = ancObj;
        }
    });
    return scene;
}



/**
 * Get the current scene's framerate.
 */
function getSceneAnimFrameRate(scene) {
    if (scene && "v3d" in scene.userData && "animFrameRate" in scene.userData.v3d) {
        return scene.userData.v3d.animFrameRate;
    }
    return 24;
}



_pGlob.animMixerCallbacks = [];

var initAnimationMixer = function() {

    function onMixerFinished(e) {
        var cb = _pGlob.animMixerCallbacks;
        var found = [];
        for (var i = 0; i < cb.length; i++) {
            if (cb[i][0] == e.action) {
                cb[i][0] = null; // desactivate
                found.push(cb[i][1]);
            }
        }
        for (var i = 0; i < found.length; i++) {
            found[i]();
        }
    }

    return function initAnimationMixer() {
        if (appInstance.mixer && !appInstance.mixer.hasEventListener('finished', onMixerFinished))
            appInstance.mixer.addEventListener('finished', onMixerFinished);
    };

}();



// animation puzzles
function operateAnimation(operation, animations, from, to, loop, speed, callback, isPlayAnimCompat, rev) {
    if (!animations)
        return;
    // input can be either single obj or array of objects
    if (typeof animations == "string")
        animations = [animations];

    function processAnimation(animName) {
        var action = v3d.SceneUtils.getAnimationActionByName(appInstance, animName);
        if (!action)
            return;
        switch (operation) {
        case 'PLAY':
            if (!action.isRunning()) {
                action.reset();
                if (loop && (loop != "AUTO"))
                    action.loop = v3d[loop];
                var scene = getSceneByAction(action);
                var frameRate = getSceneAnimFrameRate(scene);

                // compatibility reasons: deprecated playAnimation puzzles don't
                // change repetitions
                if (!isPlayAnimCompat) {
                    action.repetitions = Infinity;
                }

                var timeScale = Math.abs(parseFloat(speed));
                if (rev)
                    timeScale *= -1;

                action.timeScale = timeScale;
                action.timeStart = from !== null ? from/frameRate : 0;
                if (to !== null) {
                    action.getClip().duration = to/frameRate;
                } else {
                    action.getClip().resetDuration();
                }
                action.time = timeScale >= 0 ? action.timeStart : action.getClip().duration;

                action.paused = false;
                action.play();

                // push unique callbacks only
                var callbacks = _pGlob.animMixerCallbacks;
                var found = false;

                for (var j = 0; j < callbacks.length; j++)
                    if (callbacks[j][0] == action && callbacks[j][1] == callback)
                        found = true;

                if (!found)
                    _pGlob.animMixerCallbacks.push([action, callback]);
            }
            break;
        case 'STOP':
            action.stop();

            // remove callbacks
            var callbacks = _pGlob.animMixerCallbacks;
            for (var j = 0; j < callbacks.length; j++)
                if (callbacks[j][0] == action) {
                    callbacks.splice(j, 1);
                    j--
                }

            break;
        case 'PAUSE':
            action.paused = true;
            break;
        case 'RESUME':
            action.paused = false;
            break;
        case 'SET_FRAME':
            var scene = getSceneByAction(action);
            var frameRate = getSceneAnimFrameRate(scene);
            action.time = from ? from/frameRate : 0;
            action.play();
            action.paused = true;
            break;
        }
    }

    for (var i = 0; i < animations.length; i++) {
        var animName = animations[i];
        if (animName)
            processAnimation(animName);
    }

    initAnimationMixer();
}



// utility function used by the whenClicked, whenHovered and whenDraggedOver puzzles
function initObjectPicking(callback, eventType, mouseDownUseTouchStart, mouseButtons) {

    var elem = appInstance.renderer.domElement;
    elem.addEventListener(eventType, pickListener);
    if (v3d.PL.editorEventListeners)
        v3d.PL.editorEventListeners.push([elem, eventType, pickListener]);

    if (eventType == 'mousedown') {

        var touchEventName = mouseDownUseTouchStart ? 'touchstart' : 'touchend';
        elem.addEventListener(touchEventName, pickListener);
        if (v3d.PL.editorEventListeners)
            v3d.PL.editorEventListeners.push([elem, touchEventName, pickListener]);

    } else if (eventType == 'dblclick') {

        var prevTapTime = 0;

        function doubleTapCallback(event) {

            var now = new Date().getTime();
            var timesince = now - prevTapTime;

            if (timesince < 600 && timesince > 0) {

                pickListener(event);
                prevTapTime = 0;
                return;

            }

            prevTapTime = new Date().getTime();
        }

        var touchEventName = mouseDownUseTouchStart ? 'touchstart' : 'touchend';
        elem.addEventListener(touchEventName, doubleTapCallback);
        if (v3d.PL.editorEventListeners)
            v3d.PL.editorEventListeners.push([elem, touchEventName, doubleTapCallback]);
    }

    var raycaster = new v3d.Raycaster();

    function pickListener(event) {

        // to handle unload in loadScene puzzle
        if (!appInstance.getCamera())
            return;

        event.preventDefault();

        var xNorm = 0, yNorm = 0;
        if (event instanceof MouseEvent) {
            if (mouseButtons && mouseButtons.indexOf(event.button) == -1)
                return;
            xNorm = event.offsetX / elem.clientWidth;
            yNorm = event.offsetY / elem.clientHeight;
        } else if (event instanceof TouchEvent) {
            var rect = elem.getBoundingClientRect();
            xNorm = (event.changedTouches[0].clientX - rect.left) / rect.width;
            yNorm = (event.changedTouches[0].clientY - rect.top) / rect.height;
        }

        _pGlob.screenCoords.x = xNorm * 2 - 1;
        _pGlob.screenCoords.y = -yNorm * 2 + 1;
        raycaster.setFromCamera(_pGlob.screenCoords, appInstance.getCamera(true));
        var objList = [];
        appInstance.scene.traverse(function(obj){objList.push(obj);});
        var intersects = raycaster.intersectObjects(objList);
        callback(intersects, event);
    }
}

function objectsIncludeObj(objNames, testedObjName) {
    if (!testedObjName) return false;

    for (var i = 0; i < objNames.length; i++) {
        if (testedObjName == objNames[i]) {
            return true;
        } else {
            // also check children which are auto-generated for multi-material objects
            var obj = getObjectByName(objNames[i]);
            if (obj && obj.type == "Group") {
                for (var j = 0; j < obj.children.length; j++) {
                    if (testedObjName == obj.children[j].name) {
                        return true;
                    }
                }
            }
        }
    }
    return false;
}

// utility function used by the whenClicked, whenHovered, whenDraggedOver, and raycast puzzles
function getPickedObjectName(obj) {
    // auto-generated from a multi-material object, use parent name instead
    if (obj.isMesh && obj.isMaterialGeneratedMesh && obj.parent) {
        return obj.parent.name;
    } else {
        return obj.name;
    }
}



// whenClicked puzzle
function registerOnClick(objSelector, xRay, doubleClick, mouseButtons, cbDo, cbIfMissedDo) {

    // for AR/VR
    _pGlob.objClickInfo = _pGlob.objClickInfo || [];

    _pGlob.objClickInfo.push({
        objSelector: objSelector,
        callbacks: [cbDo, cbIfMissedDo]
    });

    initObjectPicking(function(intersects, event) {

        var isPicked = false;

        var maxIntersects = xRay ? intersects.length : Math.min(1, intersects.length);

        for (var i = 0; i < maxIntersects; i++) {
            var obj = intersects[i].object;
            var objName = getPickedObjectName(obj);
            var objNames = retrieveObjectNames(objSelector);

            if (objectsIncludeObj(objNames, objName)) {
                // save the object for the pickedObject block
                _pGlob.pickedObject = objName;
                isPicked = true;
                cbDo(event);
            }
        }

        if (!isPicked) {
            _pGlob.pickedObject = '';
            cbIfMissedDo(event);
        }

    }, doubleClick ? 'dblclick' : 'mousedown', false, mouseButtons);
}


// Describe this function...
function paso1() {
  pasos = 0;
  outline(['Torus007', 'Torus008'], 'ENABLE');

  operateAnimation('STOP', getAnimations(['ALL_OBJECTS']), null, null, 'AUTO', 1,
          function() {}, undefined, false);

      registerOnClick(['Torus007', 'Torus008'], false, false, [0,1,2], function() {
    if (pasos == 0) {
      outline(['Torus007', 'Torus008'], 'DISABLE');

      operateAnimation('PLAY', getAnimations(['GROUP', 'Amimacion_desarmado']), 1, 95, 'LoopOnce', 1,
              function() {
        pasos = 1;

        operateAnimation('PLAY', getAnimations(['GROUP', 'Amimacion_desarmado']), 96, 200, 'LoopOnce', 1,
                function() {}, undefined, false);

            }, undefined, false);

          }
  }, function() {});
  interaction1 = 0;
  interaction2 = 0;
  interaction3 = 0;
  interaction4 = 0;
  interaction5 = 0;
  interaction6 = 0;
  interaction7 = 0;
  interactionFunction(1, interaction1, 'top_arrow', 'ArrowUp', true, 200, 260, null);
}

// Describe this function...
function paso2() {
  outline('torquimetro_1', 'ENABLE');
  registerOnClick('torquimetro_1', false, false, [0,1,2], function() {
    if (pasos == 10) {
      outline('torquimetro_1', 'DISABLE');

      operateAnimation('PLAY', getAnimations(['GROUP', 'Amimacion_desarmado']), 1180, 2000, 'LoopOnce', 1,
              function() {
        outline(['Torus007.003', 'Torus008.001', 'Torus008.002'], 'ENABLE');
        pasos = 11;
      }, undefined, false);

          }
  }, function() {});
  registerOnClick(['Torus007.003', 'Torus008.001', 'Torus008.002'], false, false, [0,1,2], function() {
    if (pasos == 11) {
      outline(['Torus007.003', 'Torus008.001', 'Torus008.002'], 'DISABLE');

      operateAnimation('PLAY', getAnimations(['GROUP', 'Amimacion_desarmado']), 2020, 2260, 'LoopOnce', 1,
              function() {
        pasos = 12;
      }, undefined, false);

          }
  }, function() {});
  interaction8 = 0;
  interaction9 = 0;
  interaction10 = 0;
  interactionFunction(12, interaction8, 'top_arrow', 'ArrowUp', true, 2260, 2320, null);
}


// setTimeout puzzle
function registerSetTimeout(timeout, callback) {
    window.setTimeout(callback, 1000 * timeout);
}


// Describe this function...
function paso3() {
  outline('pieza_2_low', 'ENABLE');
  registerSetTimeout(5, function() {
    outline('pieza_2_low', 'DISABLE');

    operateAnimation('PLAY', getAnimations(['GROUP', 'Amimacion_desarmado']), 2660, 2780, 'LoopOnce', 1,
            function() {
      outline(['Torus007.005', 'Torus007.004'], 'ENABLE');
    }, undefined, false);

        });
  registerOnClick(['Torus007.005', 'Torus007.004'], false, false, [0,1,2], function() {
    if (pasos == 16) {
      outline(['Torus007.005', 'Torus007.004'], 'DISABLE');

      operateAnimation('PLAY', getAnimations(['GROUP', 'Amimacion_desarmado']), 2780, 3060, 'LoopOnce', 1,
              function() {
        pasos = 17;
      }, undefined, false);

          }
  }, function() {});
  interaction11 = 0;
  interaction12 = 0;
  interactionFunction(17, interaction11, 'top_arrow', 'ArrowUp', true, 3060, 3120, null);
}


// setHTMLElemAttribute puzzle
function setHTMLElemAttribute(attr, value, ids, isParent) {
    var elems = getElements(ids, isParent);
    for (var i = 0; i < elems.length; i++) {
        var elem = elems[i];
        if (!elem) continue;

        if (attr === 'style') {
            // NOTE: setting an attribute 'style' instead of a property 'style'
            // fixes IE11 wrong behavior
            elem.setAttribute(attr, value);
        } else if ((attr == 'href' || attr == 'src') && value instanceof Promise) {
            // resolve promise value for url-based attributes
            value.then(function(response) {
                elem[attr] = response;
            });
        } else {
            elem[attr] = value;
        }
    }
}



// callJSFunction puzzle
function getJSFunction(funcName) {
    var jsFunc = appInstance.ExternalInterface[funcName];
    if (typeof jsFunc == "function")
        return jsFunc;
    else
        return function() {};
}



// getEventProperty puzzle
function getEventProperty(prop, event) {
    if (typeof event != "undefined") {
        switch (prop) {
            case 'target.checked':
                return event.target.checked;
            case 'target.id':
                return event.target.id;
            case 'target.value':
                return event.target.value;
            case 'touches.length':
                return event.touches ? event.touches.length : 0;
            case 'touches[0].pageX':
                return event.touches[0].pageX;
            case 'touches[0].pageY':
                return event.touches[0].pageY;
            case 'touches[1].pageX':
                return event.touches[1].pageX;
            case 'touches[1].pageY':
                return event.touches[1].pageY;
            default:
                return event[prop];
        }
    }
}


// Describe this function...
function interactionFunction(func_steps, func_interaction, func_mouse, func_keyboard, func_next, func_framesFrom, func_framesTo, func_animation_counter) {
  eventHTMLElem('mousedown', func_mouse, true, function(event) {
    if (pasos == func_steps && func_interaction == 0) {

      operateAnimation('PLAY', getAnimations(['GROUP', 'Amimacion_desarmado']), func_framesFrom, func_framesTo, 'LoopOnce', 1,
              function() {
        pasos = func_steps + 1;
        console.log(pasos);
        if (func_next == true) {
          nextAnimation();
        } else {
          animation_counter = func_animation_counter;
          setHTMLElemAttribute('value', animation_counter, 'estado_animacion', true);
          getJSFunction('emitirEstadoAnimacion')();
        }
      }, undefined, false);

          }
    if (pasos == func_steps && func_interaction == 1) {

      operateAnimation('RESUME', getAnimations(['GROUP', 'Amimacion_desarmado']), null, null, 'AUTO', 1,
              function() {}, undefined, false);

          }
  });
  eventHTMLElem('mouseup', func_mouse, true, function(event) {
    if (pasos == func_steps) {
      func_interaction = 1;

      operateAnimation('PAUSE', getAnimations(['GROUP', 'Amimacion_desarmado']), null, null, 'AUTO', 1,
              function() {}, undefined, false);

          }
  });
  eventHTMLElem('keydown', ['DOCUMENT'], true, function(event) {
    if (getEventProperty('key', event) == func_keyboard) {
      if (pasos == func_steps && func_interaction == 0) {

        operateAnimation('PLAY', getAnimations(['GROUP', 'Amimacion_desarmado']), func_framesFrom, func_framesTo, 'LoopOnce', 1,
                function() {
          pasos = func_steps + 1;
          console.log(pasos);
          if (func_next == true) {
            nextAnimation();
          } else {
            animation_counter = func_animation_counter;
            setHTMLElemAttribute('value', animation_counter, 'estado_animacion', true);
            getJSFunction('emitirEstadoAnimacion')();
          }
        }, undefined, false);

            }
      if (pasos == func_steps && func_interaction == 1) {

        operateAnimation('RESUME', getAnimations(['GROUP', 'Amimacion_desarmado']), null, null, 'AUTO', 1,
                function() {}, undefined, false);

            }
    }
  });
  eventHTMLElem('keyup', ['DOCUMENT'], true, function(event) {
    if (getEventProperty('key', event) == func_keyboard) {
      if (pasos == func_steps) {
        func_interaction = 1;

        operateAnimation('PAUSE', getAnimations(['GROUP', 'Amimacion_desarmado']), null, null, 'AUTO', 1,
                function() {}, undefined, false);

            }
    }
  });
}

// Describe this function...
function nextAnimation() {
  if (pasos == 2) {
    paso1animation2();
  }
  if (pasos == 3) {
    paso1animation3();
  }
  if (pasos == 4) {
    paso1animation4();
  }
  if (pasos == 5) {
    paso1animation5();
  }
  if (pasos == 6) {
    paso1animation6();
  }
  if (pasos == 7) {
    paso1animation7();
  }
  if (pasos == 8) {
    paso1animation8();
  }
  if (pasos == 9) {
    paso1animation9();
  }
  if (pasos == 13) {
    paso2animation1();
  }
  if (pasos == 14) {
    paso2animation2();
  }
  if (pasos == 15) {
    paso2animation3();
  }
  if (pasos == 18) {
    paso3animation1();
  }
  if (pasos == 19) {
    paso3animation2();
  }
  if (pasos == 20) {
    paso3animation3();
  }
}

// Describe this function...
function paso1animation2() {
  interactionFunction(2, interaction2, 'left_arrow', 'ArrowLeft', true, 260, 380, null);
}

// Describe this function...
function paso1animation3() {
  interactionFunction(3, interaction3, 'bot_arrow', 'ArrowDown', true, 380, 440, null);
}

// Describe this function...
function paso2animation1() {
  interactionFunction(13, interaction9, 'left_arrow', 'ArrowLeft', true, 2320, 2460, null);
}

// Describe this function...
function paso3animation1() {
  interactionFunction(18, interaction11, 'left_arrow', 'ArrowLeft', true, 3120, 3260, null);
}

// Describe this function...
function paso2animation2() {
  interactionFunction(14, interaction10, 'bot_arrow', 'ArrowDown', true, 2460, 2505, null);
}

// Describe this function...
function paso3animation2() {
  interactionFunction(19, interaction12, 'bot_arrow', 'ArrowDown', true, 3260, 3300, null);
}

// Describe this function...
function paso1animation4() {

  operateAnimation('PLAY', getAnimations(['GROUP', 'Amimacion_desarmado']), 440, 560, 'LoopOnce', 1,
          function() {
    pasos = 4;
  }, undefined, false);

      registerSetTimeout(5, function() {
    outline(['Torus007.002', 'Torus007.001', 'Torus008.003'], 'ENABLE');
    registerOnClick(['Torus007.002', 'Torus007.001', 'Torus008.003'], false, false, [0,1,2], function() {
      if (pasos == 4) {
        outline(['Torus007.002', 'Torus007.001', 'Torus008.003'], 'DISABLE');

        operateAnimation('PLAY', getAnimations(['GROUP', 'Amimacion_desarmado']), 560, 730, 'LoopOnce', 1,
                function() {
          pasos = 5;
          nextAnimation();
        }, undefined, false);

            }
    }, function() {});
  });
}

// Describe this function...
function paso2animation3() {

  operateAnimation('PLAY', getAnimations(['GROUP', 'Amimacion_desarmado']), 2505, 2660, 'LoopOnce', 1,
          function() {
    pasos = 16;
    animation_counter = 2;
    setHTMLElemAttribute('value', animation_counter, 'estado_animacion', true);
    getJSFunction('emitirEstadoAnimacion')();
    console.log('Paso 2 terminado');
  }, undefined, false);

      }

// Describe this function...
function paso3animation3() {

  operateAnimation('PLAY', getAnimations(['GROUP', 'Amimacion_desarmado']), 3300, 3460, 'LoopOnce', 1,
          function() {
    pasos = 21;
    animation_counter = 3;
    setHTMLElemAttribute('value', animation_counter, 'estado_animacion', true);
    getJSFunction('emitirEstadoAnimacion')();
    console.log('Paso 3 terminado');
  }, undefined, false);

      }

// Describe this function...
function paso1animation5() {
  interactionFunction(5, interaction4, 'right_arrow', 'ArrowRight', true, 730, 830, null);
}

// Describe this function...
function paso1animation6() {
  interactionFunction(6, interaction5, 'top_arrow', 'ArrowUp', true, 830, 880, null);
}

// Describe this function...
function paso1animation7() {
  interactionFunction(7, interaction6, 'left_arrow', 'ArrowLeft', true, 880, 980, null);
}

// Describe this function...
function paso1animation8() {
  interactionFunction(8, interaction7, 'bot_arrow', 'ArrowDown', true, 980, 1040, null);
}

// Describe this function...
function paso1animation9() {

  operateAnimation('PLAY', getAnimations(['GROUP', 'Amimacion_desarmado']), 1040, 1180, 'LoopOnce', 1,
          function() {
    pasos = 10;
    animation_counter = 1;
    setHTMLElemAttribute('value', animation_counter, 'estado_animacion', true);
    getJSFunction('emitirEstadoAnimacion')();
    console.log('Paso 1 terminado');
  }, undefined, false);

      }


correas = ['Object12923', 'Object12923.001', 'Object12923.002', 'Object12923.003', 'Object12923.004', 'Object12923.005', 'Object12923.006', 'garra_1', 'garra_1.001', 'garra_1.002', 'garra_1.003', 'garra_1.004', 'garra_1.005', 'garra_1.006', 'seguro_garra_1', 'seguro_garra_1.001', 'seguro_garra_1.002', 'seguro_garra_1.003', 'seguro_garra_1.004', 'seguro_garra_1.005', 'seguro_garra_1.006', 'Object12925', 'Object12925.001', 'Object12925.002', 'Object12925.003', 'Object12925.004', 'Object12925.005', 'Object12925.006', 'Object12925.007', 'garra_2', 'garra_2.001', 'garra_2.002', 'garra_2.003', 'garra_2.004', 'garra_2.005', 'garra_2.006', 'garra_2.007', 'seguro_garra_2', 'seguro_garra_2.001', 'seguro_garra_2.002', 'seguro_garra_2.003', 'seguro_garra_2.004', 'seguro_garra_2.005', 'seguro_garra_2.006', 'seguro_garra_2.007'];
count = 0;

animation_counter = 0;
eventHTMLElem('click', 'pro1-paso1', true, function(event) {
  paso1();
});
eventHTMLElem('click', 'pro1-paso2', true, function(event) {
  paso2();
});
eventHTMLElem('click', 'pro1-paso3', true, function(event) {
  paso3();
});



} // end of PL.init function

})(); // end of closure

/* ================================ end of code ============================= */
